Update patch set 7
Patch Set 7:

Last failure due to link to test code not added to commit message.

    ImportError: No module named 'zaza.openstack.charm_tests.ovn'

Patch-set: 7
Label: Verified=0